### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by xiaoerhei** [keyunluo/python-ffm#2]
>>> import ffm 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/hgfs/VM_WorkFolder/software/python-ffm/ffm/__init__.py", line 1, in <module>
    from .ffm import FFMData, FFM, read_model
  File "/mnt/hgfs/VM_WorkFolder/software/python-ffm/ffm/ffm.py", line 5, in <module>
    libffm_file = [i for i in os.listdir(path) if i.startswith('libffm.')][0]
IndexError: list index out of range

**Comment by keyunluo** [comment]
> libffm_file = [i for i in os.listdir(path) if i.startswith('libffm.')][0]

You could set it with absolute path for some versions of os. (/mnt/hgfs/VM_WorkFolder/software/python-ffm/ffm/libffm.cpython-35m-x86_64-linux-gnu.so)
