### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by lxin81** [keyunluo/python-ffm#4]
Traceback (most recent call last):
  File "sklearn-example.py", line 7, in <module>
    from ffm import FFM, FFMFormatPandas, FFMData, save_data
  File "/media/lx/项目/tx/python-ffm/ffm/__init__.py", line 1, in <module>
    from .ffm import *
  File "/media/lx/项目/tx/python-ffm/ffm/ffm.py", line 5, in <module>
    libffm_file = [i for i in os.listdir(path) if i.startswith('libffm.')][0]
IndexError: list index out of range

**Comment by zenwan** [comment]
同样问题
